# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Empfehlung: Stabile Version statt 3.13

# Sphinx explizit konfigurieren
sphinx:
  configuration: docs/conf.py # Sagt Sphinx, wo die Konfiguration liegt
  # Fail on warning kann nützlich sein:
  # fail_on_warning: true

# Ggf. Abhängigkeiten installieren
python:
  install:
    - requirements: docs/requirements.txt # Falls vorhanden
    # Oder: - method: pip
    #         path: .
