# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13" # Überlege, 3.11 oder 3.12 für bessere Kompatibilität zu nutzen

sphinx:
   configuration: docs/conf.py

# Installiere Python-Abhängigkeiten
python:
   install:
   - requirements: docs/requirements.txt # Pfad zur Requirements-Datei
   # Optional: Installiere dein Projekt selbst, wenn autodoc es braucht
   # - method: pip
   #   path: .
