# Generated by Django 5.1.7 on 2025-03-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_package_active_package_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='recipes',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
