# Generated by Django 5.1.7 on 2025-03-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_package_recipes_delete_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmaterial',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='additionalmaterial',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='Is Example'),
        ),
        migrations.AlterField(
            model_name='additionalmaterial',
            name='packages',
            field=models.ManyToManyField(blank=True, to='cms.package', verbose_name='Packages'),
        ),
        migrations.AlterField(
            model_name='additionalmaterial',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='Is Example'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='package',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='package',
            name='additional_materials',
            field=models.ManyToManyField(blank=True, related_name='included_in_packages', to='cms.additionalmaterial', verbose_name='Additional Materials'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Discount End Date'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Discount Start Date'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=50, verbose_name='Duration Unit'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_lifetime',
            field=models.BooleanField(default=False, verbose_name='Is Lifetime'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Is Popular'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is Recurring'),
        ),
        migrations.AlterField(
            model_name='package',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='included_in_packages', to='cms.lesson', verbose_name='Lessons'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
