# Dockerfile_django
# Use an official Python runtime as a parent image
FROM python:3.13.2-alpine AS base

# Set the working directory to /app
WORKDIR /app

# Install necessary system packages
RUN apk add --no-cache mariadb-connector-c-dev gcc musl-dev

# Copy the current directory contents into the container at /app
COPY frontend/requirements_django.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the code
COPY frontend/cofo_django /app/

# Expose port 8000 for the Django server
EXPOSE 8000
