version: "3.9" # Definiert die Version der Docker Compose-Datei.

services:
  db: # Definiert den MariaDB-Datenbankdienst.
    build: # Konfiguriert den Build des Datenbank-Images.
      context: . # Setzt das Build-Kontext auf das aktuelle Verzeichnis.
      dockerfile: Dockerfile_mariadb # Gibt das Dockerfile für den Datenbank-Build an.
    environment: # Setzt Umgebungsvariablen für den Datenbankcontainer.
      MYSQL_ROOT_PASSWORD: jede2 # Setzt das Root-Passwort für die MariaDB-Datenbank. (Sicherheitshinweis: Verwenden Sie stärkere Passwörter in Produktionsumgebungen.)
      MYSQL_DATABASE: conscious_fit # Erstellt die Datenbank "conscious_fit" beim Start.
    ports: # Ordnet Ports zwischen Host und Container zu.
      - "3306:3306" # Macht den MariaDB-Port 3306 auf dem Host zugänglich.
    volumes: # Bindet Volumes für persistente Datenspeicherung.
      - mariadb_data:/var/lib/mysql # Speichert die Datenbankdaten im benannten Volume "mariadb_data".

  backend: # Definiert den Python-Backenddienst.
    build: # Konfiguriert den Build des Backend-Images.
      context: . # Setzt das Build-Kontext auf das aktuelle Verzeichnis.
      dockerfile: Dockerfile_python # Gibt das Dockerfile für den Backend-Build an.
    ports: # Ordnet Ports zwischen Host und Container zu.
      - "8000:8000" # Macht den Backend-Port 8000 auf dem Host zugänglich.
    depends_on: # Definiert Abhängigkeiten zwischen Diensten.
      - db # Stellt sicher, dass der "db"-Dienst vor dem "backend"-Dienst gestartet wird.
    environment: # Setzt Umgebungsvariablen für den Backend-Container.
      DATABASE_URL: mysql+pymysql://root:jede2@db/conscious_fit # Setzt die Datenbankverbindungs-URL.

volumes: # Definiert benannte Volumes für persistente Datenspeicherung.
  mariadb_data: # Definiert das Volume "mariadb_data".
