version: "3.8"

services:
  db_test:
    image: mariadb:10.11.6  # Use the official MariaDB image
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - consciousfit_data_test:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysql", "-u", "${DB_USER}", "-p${DB_PASSWORD}", "-e", "SELECT 1;"] # Datenbank Healthcheck
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network_test

  backend_test:
    build:
      context: ../
      dockerfile: docker/Dockerfile_python.test
    ports:
      - "8001:8000"
    depends_on:
      - db_test
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db_test:3306/${DB_DATABASE} # Construct database URL
      - SECRET_KEY=${SECRET_KEY}
      - ENV=test
      - DEBUG=${DEBUG}
    volumes:
      - ../backend/app:/app  # Für Entwicklung
      - ../backend/tests:/tests  # Für Entwicklung
      - ../.cache:/root/.cache
    command: ["sh", "-c", "sleep 5 && while true; do pytest /tests --html=report.html --self-contained-html; sleep 9; done"]
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] # Assumes /health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network_test

volumes:
  consciousfit_data_test:

networks:
  app-network_test:
    driver: bridge
