#FROM python:3.13.2-slim-bookworm
FROM python:3.13.2-alpine AS base

WORKDIR /app

# Install necessary system packages
RUN apk add --no-cache mariadb-connector-c-dev gcc musl-dev

# Install Python dependencies
COPY docker/requirements.test.txt ./
RUN pip install --no-cache-dir -r requirements.test.txt

# Copy the application code
COPY backend/app /app
COPY backend/tests /tests 