version: "3.8"

services:
  db:
    image: mariadb:10.11  # Use the official MariaDB image
    environment:
      MYSQL_ROOT_PASSWORD: jede2  # Change this in production!
      MYSQL_DATABASE: conscious_fit
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"  # Expose only if needed for external access
    volumes:
      - consciousfit_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile_python
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
      - DB_NAME=conscious_fit
      - DB_PASSWORD=app_password
      - DB_HOST=db
      - DB_USER=app_user
    volumes:
      - ../backend/app:/app  # Use relative path for consistency
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] # Assumes /health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # <-- Use Uvicorn
# ... (rest of your docker-compose.yml)

volumes:
  consciousfit_data:

networks:
  app-network:
    driver: bridge
