version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: jede2
      MYSQL_DATABASE: conscious_fit
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "app_user", "-papp_password"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile_python
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://app_user:app_password@db/conscious_fit # Direktes Passwort, oder Umgebungsvariable verwenden.
      DB_NAME: conscious_fit
      DB_PASSWORD: app_password
      DB_HOST: db
      DB_USER: app_user
    volumes:
      - ./backend:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
