version: "3.8"

services:
  db:
    image: mariadb:10.11.6  # Use the official MariaDB image
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - consciousfit_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysql", "-u", "${DB_USER}", "-p${DB_PASSWORD}", "-e", "SELECT 1;"] # Datenbank Healthcheck
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile_python
    env_file:
      - ./.env # Hinzugefügte Zeile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../backend/app:/app  # Für Entwicklung
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] # Assumes /health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

volumes:
  consciousfit_data:

networks:
  app-network:
    driver: bridge
