# Generated by Django 5.1.7 on 2025-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_disease_ingredient_vitamin_a_ingredient_vitamin_b1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='reference_unit',
            field=models.CharField(default='100g', max_length=50),
        ),
    ]
