# Generated by Django 5.1.7 on 2025-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_reference_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='reference_quantity',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reference_unit',
            field=models.CharField(default='g', max_length=50),
        ),
    ]
