# Generated by Django 5.1.7 on 2025-03-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredient_reference_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(default='g', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientHouseholdMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('household_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.householdmeasurement')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_measurements', to='ingredients.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ingredients/')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ingredients.ingredient')),
            ],
        ),
    ]
