# Generated by Django 5.1.7 on 2025-03-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_householdmeasurement_ingredienthouseholdmeasurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='householdmeasurement',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='householdmeasurement',
            name='unit',
            field=models.CharField(default='g', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='ingredients.allergen', verbose_name='Allergens'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='can_cause',
            field=models.ManyToManyField(blank=True, related_name='causing_ingredients', to='ingredients.disease', verbose_name='Can Cause'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fat'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fiber'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='kcal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='kcal'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='not_recommended_for',
            field=models.ManyToManyField(blank=True, related_name='not_recommended_ingredients', to='ingredients.disease', verbose_name='Not Recommended For'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reference_quantity',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Reference Quantity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reference_unit',
            field=models.CharField(default='g', max_length=50, verbose_name='Reference Unit'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Sodium'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin A'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B1'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B12'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B2'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B3'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B5'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B6'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B7'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_b9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin B9'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin C'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin D'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin E'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamin_k',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Vitamin K'),
        ),
        migrations.AlterField(
            model_name='ingredienthouseholdmeasurement',
            name='household_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.householdmeasurement', verbose_name='Household Measurement'),
        ),
        migrations.AlterField(
            model_name='ingredienthouseholdmeasurement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_measurements', to='ingredients.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredienthouseholdmeasurement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ingredientimage',
            name='image',
            field=models.ImageField(upload_to='ingredients/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ingredientimage',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ingredients.ingredient', verbose_name='Ingredient'),
        ),
    ]
