# Generated by Django 5.2 on 2025-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('recipes', '0004_recipe_author_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ManyToManyField(to='recipes.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeContent',
        ),
    ]
