# Generated by Django 5.2 on 2025-04-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_recipebundle_delete_recipecontent'),
        ('recipes', '0004_recipe_author_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipebundle',
            options={'verbose_name': 'Recipe Bundle', 'verbose_name_plural': 'Rezept-Bundles'},
        ),
        migrations.AddField(
            model_name='recipebundle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipebundle',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Bundle Name'),
        ),
        migrations.AlterField(
            model_name='recipebundle',
            name='recipes',
            field=models.ManyToManyField(to='recipes.recipe', verbose_name='Included recipes'),
        ),
    ]
