# Generated by Django 5.2 on 2025-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_recipebundle_options_recipebundle_description_and_more'),
        ('recipes', '0004_recipe_author_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipebundle',
            options={'verbose_name': 'Recipe Bundle', 'verbose_name_plural': 'Recipe Bundles'},
        ),
        migrations.AddField(
            model_name='recipebundle',
            name='includes_all_recipes',
            field=models.BooleanField(default=False, help_text='If checked, this bundle represents all available recipes, regardless of the selection above.', verbose_name='Always include all recipes'),
        ),
        migrations.AlterField(
            model_name='recipebundle',
            name='recipes',
            field=models.ManyToManyField(blank=True, help_text="Select specific recipes if 'Always include all recipes' is not checked.", to='recipes.recipe', verbose_name='Included Recipes'),
        ),
    ]
