# Generated by Django 5.1.7 on 2025-04-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='openfoodfacts_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
