# Generated by Django 5.1.7 on 2025-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(default='g', max_length=50),
        ),
    ]
