# Generated by Django 5.1.7 on 2025-03-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_alter_allergen_name_alter_disease_name_and_more'),
        ('recipes', '0002_alter_dishingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishingredient',
            name='household_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.householdmeasurement', verbose_name='Household Measurement'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient', verbose_name='Ingredient'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='recipes.recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='Is Example'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preparation Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
