# Generated by Django 5.2 on 2025-04-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredient_name_ingredient_openfoodfacts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='_Unbekannt', max_length=200),
            preserve_default=False,
        ),
    ]
