# Generated by Django 5.1.7 on 2025-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_dishingredient_household_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='unit',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
