# Generated by Django 5.1.7 on 2025-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focoquiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='choice_1_count',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='choice_2_count',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='choice_3_count',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_choice_1_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_choice_2_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_choice_3_result',
            field=models.BooleanField(default=False),
        ),
    ]
